---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx virtual host
  ansible.builtin.template:
    src: nginx_vhost.j2
    dest: /etc/nginx/sites-available/expresscart
  notify: Restart Nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/expresscart
    dest: /etc/nginx/sites-enabled/expresscart
    state: link

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
